// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_CopyActor","status":true,"description":"This plugin allows you to equip items as party members","parameters":{}},
{"name":"ME_InstanceActor","status":true,"description":"This plugin allows you to create actors with specific variety of extra parameters","parameters":{"stats":"","minhp":"-200","maxhp":"200","minmp":"-100","maxmp":"100","minatk":"-10","maxatk":"10","mindef":"-10","maxdef":"10","minmat":"-10","maxmat":"10","minmde":"-10","maxmde":"10","minagi":"-10","maxagi":"10","minluck":"-10","maxluck":"10"}}
];
