// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_CopyActor","status":true,"description":"This plugin allows you to equip items as party members","parameters":{}},
{"name":"ME_InstanceActor","status":true,"description":"This plugin allows you to create actors with specific variety of extra parameters","parameters":{"minhp":"-400","maxhp":"400","minmp":"-200","maxmp":"200","minatk":"-40","maxatk":"40","mindef":"-40","maxdef":"40","minmat":"-40","maxmat":"40","mimde":"-40","maxmde":"40","minagi":"-40","maxagi":"40","minluck":"-40","maxluck":"40"}}
];
